version: "3.9"
services:
  backend:
    container_name: ludo-backend
    build:
      context: ./ludo-backend/.
      target: development
    volumes:
      - ./ludo-backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 3001:3001
    command: npm run start:dev
    env_file:
      - ./ludo-backend/.env
    depends_on:
      - mongo
  frontend:
    container_name: ludo-frontend
    build:
      context: ./ludo-frontend/.
    volumes:
      - ./ludo-frontend:/usr/src/app
      - /usr/src/node_modules
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    env_file:
      - ./ludo-frontend/.env
    depends_on:
      - mongo
      - backend
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ludo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
